CREATE TABLE PERSON (
  PERSON_NAME   VARCHAR(100) NOT NULL,
  PERSON_EMAIL  VARCHAR(100) NOT NULL
);

CREATE TABLE PERSON_TO_DEPARTMENT (
  PERSON_NAME         VARCHAR(100) NOT NULL,
  DEPARTMENT_NAME     VARCHAR(100) NOT NULL,
);
